server:
  tomcat:
    max-threads: 200
    min-threads: 50

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecom_db
    username: root
    password: 1234
#    hikari:
#      maximum-pool-size: 50
#      min-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

#logging:
#  level:
#    com.zaxxer.hikari: TRACE
#    com.zaxxer.hikari.HikariConfig: DEBUG
